# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               PacketBrothers
tagline:             'A place for network dreamers'
description:         'Made by <a href="https://twitter.com/BrothersPacket" target="_blank">@BrothersPacket</a>.'
url:                 http://packetbrothers.github.io/blog
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Packet Brother
  url:               https://twitter.com/BrothersPacket
  email:             packetbrothers@gmail.com

# Custom vars
version:             1.0.0
